// Forge generation (DESIGN §10/D14). The pure half, `specToFiles`, turns a
// resolved ForgeSpec into a path→content map: it inlines every prompt into its
// own file and emits a pack.json whose agents/rubrics/persona reference those
// files by "./"-relative path — exactly the shape `loadPack` + `validatePack`
// expect. The impure half, `writePack`, is a thin disk writer over that map. The
// split is what lets us assert the generated bytes without touching the filesystem.

import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, join, sep } from 'node:path';
import type { ForgeSpec } from './spec.ts';
import { slug } from './spec.ts';

/** A generated pack as a map of "./"-relative path → file content. */
export type FileMap = ReadonlyMap<string, string>;

function agentPath(name: string): string {
  return `./agents/${slug(name)}.md`;
}
function rubricPromptPath(name: string): string {
  return `./rubrics/${slug(name)}.prompt.md`;
}
function rubricValidatorPath(name: string): string {
  return `./rubrics/${slug(name)}.validator.mjs`;
}

// Build the manifest object first so the file map and pack.json never drift.
function buildManifest(spec: ForgeSpec): Record<string, unknown> {
  const manifest: Record<string, unknown> = {
    schema: 1,
    name: spec.name,
    version: spec.version,
    description: spec.description,
    persona: './persona.md',
    grants: [...spec.grants],
    agents: spec.agents.map((a) => ({
      name: a.name,
      model: `tier:${a.tier}`,
      tools: [...a.tools],
      prompt: agentPath(a.name),
    })),
    rubrics: spec.rubrics.map((r) => ({
      name: r.name,
      prompt: rubricPromptPath(r.name),
      validator: rubricValidatorPath(r.name),
    })),
    modelTiers: { ...spec.tiers },
  };
  if (spec.onboarding !== undefined) manifest['onboarding'] = './onboarding.md';
  if (spec.memory !== undefined) {
    const mem: Record<string, string> = {};
    if (spec.memory.seeds !== undefined) mem['seeds'] = './memory/seeds.md';
    if (spec.memory.promotion !== undefined) mem['promotion'] = spec.memory.promotion;
    if (Object.keys(mem).length > 0) manifest['memory'] = mem;
  }
  return manifest;
}

/** Pure: ForgeSpec → path→content map. Deterministic; no IO. */
export function specToFiles(spec: ForgeSpec): FileMap {
  const files = new Map<string, string>();

  const manifest = buildManifest(spec);
  files.set('./pack.json', `${JSON.stringify(manifest, null, 2)}\n`);
  files.set('./persona.md', ensureTrailingNewline(spec.persona));

  for (const a of spec.agents) files.set(agentPath(a.name), ensureTrailingNewline(a.prompt));

  for (const r of spec.rubrics) {
    files.set(rubricPromptPath(r.name), ensureTrailingNewline(r.prompt));
    files.set(rubricValidatorPath(r.name), ensureTrailingNewline(r.validator));
  }

  if (spec.onboarding !== undefined) files.set('./onboarding.md', ensureTrailingNewline(spec.onboarding));
  if (spec.memory?.seeds !== undefined) {
    files.set('./memory/seeds.md', ensureTrailingNewline(spec.memory.seeds.join('\n')));
  }

  return files;
}

function ensureTrailingNewline(s: string): string {
  return s.endsWith('\n') ? s : `${s}\n`;
}

/** Impure: write a FileMap under `root`, creating parent directories as needed. */
export async function writePack(root: string, files: FileMap): Promise<void> {
  for (const [rel, content] of files) {
    const abs = join(root, rel.replace(/^\.\//, '').split('/').join(sep));
    await mkdir(dirname(abs), { recursive: true });
    await writeFile(abs, content, 'utf8');
  }
}

/** Convenience: spec → files → disk in one call. Returns the file map written. */
export async function generatePack(root: string, spec: ForgeSpec): Promise<FileMap> {
  const files = specToFiles(spec);
  await writePack(root, files);
  return files;
}
